[versions]
# Android Gradle Plugin version
agp = "8.2.2"

# Core library versions
junit = "4.13.2"
androidxJunit = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
securityCrypto = "1.1.0-alpha06"
gson = "2.10.1"

[libraries]
# Core Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# AndroidX & Material Design
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Security & Data
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
# Note the alias name: android-application
android-application = { id = "com.android.application", version.ref = "agp" }
