[versions]
agp = "8.3.0"
junit = "4.13.2"
ext-junit = "1.3.0"
espresso-core = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
security-crypto = "1.0.0" # Sticking to the stable 1.0.0 as 1.1.0 is the one with deprecations
gson = "2.10.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security-crypto" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
